image: ubuntu:16.04
pipelines:
 branches:
  master:
   - step:
      script:
      - apt-get -yq update && apt-get -yqq install ssh
      - ssh-keyscan $HOST >> ~/.ssh/known_hosts
      - echo $PRIVATE_KEY > ~/.ssh/id_rsa.tmp
      - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa
      - sh bin/deploy.sh
  develop:
    - step:
       script:
        - apt-get -yq update && apt-get -yqq install ssh
        - ssh-keyscan $HOST >> ~/.ssh/known_hosts
        - echo $PRIVATE_KEY > ~/.ssh/id_rsa.tmp
        - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
        - chmod 400 ~/.ssh/id_rsa
        - sh bin/deploy.sh