image: node:latest
pipelines:
 branches:
  master:
   - step:
      script:
      - export NODE_ENV="$NODE_ENV_TEST"
      - npm install
      - npm test
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t $DOCKER_REPO:latest .
      - docker push $DOCKER_REPO:latest
      - ssh-keyscan $HOST >> ~/.ssh/known_hosts
      - echo $PRIVATE_KEY > ~/.ssh/id_rsa.tmp
      - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa
      - sh bin/deploy-w-test.sh
      services:
      - postgresdb
definitions:
 services:
  postgresdb:
   image: postgres
   environment:
    POSTGRES_DB: 'pipelines'
    POSTGRES_USER: 'test_user'
    POSTGRES_PASSWORD: 'test_user_password'
options:
 docker: true